export const TABLES = {
    T_SYS_REGION_TIMEZONE: "T_SYS_REGION_TIMEZONE",
    T_POS_RECEIPT_FISCAL_PRINTER: "T_POS_RECEIPT_FISCAL_PRINTER",
    T_SYS_PARAMETERS: "T_SYS_PARAMETERS",
    DESTINATARIO: "DESTINATARIO",
    T_XSC_CONFIG: "T_XSC_CONFIG",
    T_PA_EXTERNAL_DASHBOARD: "T_PA_EXTERNAL_DASHBOARD",
    T_POS_PAYFORM: "T_POS_PAYFORM",
}